version: '3.8'
services:
  api:
    build:
      context: .
    command: ["node", "api.js"]
    ports:
      - "4000:4000"
    volumes:
      - .:/app
  server:
    build:
      context: .
    command: ["node", "server.js"]
    ports:
      - "3000:3000"
    volumes:
      - .:/app
